version: '3'
services:
  acquisition_node_watchtowerXX:
      image: duckietown/cslam-acquisition:x86
      environment:
        - ACQ_DEVICE_MODE=live
        - ACQ_ROS_MASTER_URI_DEVICE=watchtowerXX.local
        - ACQ_ROS_MASTER_URI_DEVICE_IP=XXX.XXX.XXX.XXX
        - ACQ_SERVER_MODE=live
        - ACQ_ROS_MASTER_URI_SERVER=watchtowerXX.local
        - ACQ_ROS_MASTER_URI_SERVER_IP=XXX.XXX.XXX.XXX
        - ACQ_DEVICE_NAME=watchtowerXX
        - ACQ_TOPIC_RAW=camera_node/image/compressed
        - ACQ_TOPIC_CAMERAINFO=camera_node/camera_info
        - ACQ_TAG_SIZE=0.065
        - ACQ_POSES_TOPIC=poses
        - ACQ_TEST_STREAM=0
        - ACQ_BEAUTIFY=0
        - ACQ_IMAGE_PROCESSORS=3
        - ACQ_DETECTOR_TYPE=DFC
      network_mode: "host"
      restart: always
